### ISSUE TITLE
Register new user

### ISSUE THREAD

**Issue by 4rthb** [4rthb/swop.it#5]
Excerpt from the report;

![image](https://user-images.githubusercontent.com/57924116/184293204-5a166c5b-c307-44c4-932d-7524e200f57f.png)

 - Items must be saved on the dummy file "users.json" **INSIDE** the "models" folder in the JSON format.
 - Integration with the database will be implemented on later stages of the project.

**Comment by tiagotschmidt** [comment]
Alice :)
